### ISSUE TITLE
Facilitate Project Reflection - IRS DF Phase 1 

### ISSUE THREAD

**Issue by kelleyconfer** [18F/TLC-crew#243] opened 2023-05-30 21:49 UTC
### A description of the work
The IRS Direct File team is in need of a facilitator for a project reflection during the week of 6/5. There are team times available on Tuesdays and Thursdays that can work, or happy to assist scheduling a new time. 

### Point of contact on this issue
Who can we follow-up with if we have questions?
@kelleyconfer and @rrefoy 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

How much time do you anticipate this work taking?
3-4 hours 

### Acceptance Criteria

- [ ] What does "done" look like?

A summarized project reflection posted in #project-reflections

**Comment by MelissaBraxton** [comment] 2023-06-05 21:23
@kelleyconfer  - Is this a dupe of #145?

**Comment by kelleyconfer** [comment] 2023-06-05 22:25
@MelissaBraxton Yes it is, great catch! We can close #145 so as not to have duplicates. Thank you!

**Comment by kelleyconfer** [comment] 2023-06-06 15:03
@MelissaBraxton and @alexbielen will we be able to have a facilitator for this final reflection? Thank you!

**Comment by mel-keene-gsa** [comment] 2023-06-20 15:33
@MelissaBraxton here's the [half-filled conversation guide](https://docs.google.com/document/d/1ULXpHopVtKhmB7nx-StNCRJ-6ZgN6NyCMulARurBPCM/edit?usp=sharing) for this (just shared with the TLC Crew). I have the raw notes, which I'd prefer to share privately with whoever takes this on, as I said they would be anonymous in the session. Happy to pair with whoever takes on Part 2 to fill out the summary!

**Comment by MelissaBraxton** [comment] 2023-06-20 18:16
Remaining steps for whoever carries @mel-keene-gsa 's work forward

- [ ] schedule another conversation with the team to discuss the remaining prompts
- [ ] complete summary
- [ ] get the team to review
- [ ] post to the reflection channel
- [ ] add to airtable

**Closed** 2023-06-29 16:13 UTC
Labels: Bet 2, Initiative 3
