### ISSUE TITLE
Replatforming: Explore possible solutions to path redirect issue

### ISSUE THREAD

**Issue by alexbielen** [18F/TLC-crew#372] opened 2023-07-31 21:25 UTC
### A description of the work

The redirect issue: It appears that the default way to do [Cloud.gov Pages redirects](https://github.com/cloud-gov/pages-redirects/) will strip out path information. 

For example, in the past year, 2.4k users clicked through to https://accessibility.18f.gov/checklist/  from https://www.gov.uk/service-manual/helping-people-to-use-your-service/understanding-wcag  or https://www.gov.uk/service-manual/helping-people-to-use-your-service/testing-for-accessibility.  (:thank-you: @michelle-rago ). With the default redirect it appears that we would lose the `/checklist/` path, so users from the gov.uk pages mentioned above would be redirected to {newname}.18f.gov/guides/accessibility (the “home” page of the accessibility guide) and not directly to the “checklist” page.

We'd like to explore possible solutions to this issue. 

As a first step, we'd like to dig in with the Cloud.gov Pages team and see if there are changes that we could make to the Cloud.gov Pages redirects that will enable this. 

### Point of contact on this issue

@alexbielen 

**Skills needed**

- [x] Engineering

### Acceptance Criteria

- [ ] Confirm that the default solution will indeed strip out path information
- [ ] Communicate with relevant stakeholders at Cloud.gov Pages and explain the issue to them
- [ ] Document their response and create any relevant  follow-on work in the TLC Crew repo

**Comment by beechnut** [comment] 2023-08-01 20:02
Problem **invalidated**: Andrew Burnes sent [this config block](https://github.com/cloud-gov/pages-redirects/blob/08be978a601e36abca8926a7e86f72fcd4e8c007/templates/_federalist-redirects.njk#L95-L100) to show how we'd preserve paths — the `$request_uri` var is how we're preserving the path.

**Comment by beechnut** [comment] 2023-08-01 20:21
Doubly confirmed with Drew Bollinger. @alexbielen I think this can safely be marked as closed.

**Comment by alexbielen** [comment] 2023-08-02 16:15
Great -- thanks for digging into this! Before we close let's create an example of the NGINX config that does the following: 

Redirect  https://accessibility.18f.gov/checklist to https://guides.18f.gov/accessibility/checklist 

And then add that to the [Tech Spec section on redirects](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#heading=h.6jx84cd16951)

**Comment by beechnut** [comment] 2023-08-02 16:22
@alexbielen Since this is a lift-and-shift, I would assume accessibility.18f.gov/checklist to simply point to the replatformed content, not result in a redirect. Is there a decision recorded somewhere that we should be changing all of the Guides' URLs?

**Comment by alexbielen** [comment] 2023-08-02 19:57
Yup! In the tech spec there is a section about the [new domain name](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#heading=h.gsjmgji891xi). The guides will be directories under a single 18F subdomain in support of making it "one product".

**Comment by beechnut** [comment] 2023-08-03 13:34
@alexbielen [Added an example to the doc](https://docs.google.com/document/d/1lByvjE1xwtdKzn4jhUGYiwMKJLBJug6TqatcKVe2C5o/edit#heading=h.us1d3c54gbi0)

**Closed** 2023-08-03 14:56 UTC
Labels: engineering, Bet 2
