### ISSUE TITLE
Improve load time performance of replatformed Guides and Methods

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/TLC-crew#343] opened 2023-07-18 15:49 UTC
Part of the Guides Replatforming Epic #269

### A description of the work
The current cloud.gov pages preview of the guides and methods can take ~30 seconds per page to load, which makes working with the preview difficult, and will be a nuisance to visitors should the problem persist into production. 

One possible source of this long load time is a large CSS file (~2MB), but there may be other factors as well that will need to researched.

### Point of contact on this issue
Who can we follow-up with if we have questions?

### Reproduction steps (if necessary)
Visit [federalist-864a0936-e148-4df8-8602-6b0992887566.sites.pages.cloud.gov/site/18f/approaches/](https://federalist-864a0936-e148-4df8-8602-6b0992887566.sites.pages.cloud.gov/site/18f/approaches/) and note the load time.

**WIFI Speed**

![Wifi speed test results showing 98.3 Mbps downald 17.7 Mbps upload](https://github.com/18F/TLC-crew/assets/52677065/e1ffaa31-cd06-4510-9bed-c9d2c7444b2b)

![Chrome developer tools network pane for the accessibility guide federalist preview](https://github.com/18F/TLC-crew/assets/52677065/348fa552-4d85-45e2-87f6-7f8d5e23ff5b)

**Billable?**

- [ ] Yes
- [X] No

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
3-6 hours

### Acceptance Criteria

- [ ] As a site visitor I can open the pages of the site without having to wait for long – the load time takes 5 seconds or less.

**Comment by MelissaBraxton** [comment] 2023-07-18 18:29
Since Logan is out for the first half of the increment, we may need to downsize this to researching the problem and solution and saving implementation for the next increment.

**Comment by beechnut** [comment] 2023-07-19 13:36
I cannot reproduce this issue: after visiting a number of pages, including the one linked, my max pageload time is 1300ms.

@igorkorenfeld (or anyone else who has encountered this), could you post a screenshot of your network pane for a load of the page in **Reproduction steps**, as well as a screenshot of your network speed [using Google's speed test](https://www.google.com/search?q=speed+test)?

**Comment by igorkorenfeld** [comment] 2023-07-19 19:48
Will follow up with screenshots tomorrow

**Comment by beechnut** [comment] 2023-07-20 14:28
Thank you for posting those! That is one heck of an unfortunate load time. (I'm also finding it odd that I'm getting < 2s load times for the exact same page, and we're not that far apart geographically so this is now quite the mystery.)

**Comment by beechnut** [comment] 2023-07-21 15:15
Waiting for @loganmeetsworld to return before starting in on this further.

**Comment by igorkorenfeld** [comment] 2023-07-21 18:04
To make things more complicated, sameish interest speed, only a few seconds to load today. 


![Screenshot of chrome network pane showing 4.8 second page load](https://github.com/18F/TLC-crew/assets/52677065/842fd600-21f0-4f85-a84c-9bcadbd252b8)

**Comment by loganmeetsworld** [comment] 2023-07-24 17:42
Unfortunately I cannot replicate this on my machine or on an automated browser.

**Comment by loganmeetsworld** [comment] 2023-07-25 16:09
We are closing this for now given we cannot currently replicate but are adding things to the tech spec around checking load times.

**Closed by loganmeetsworld** 2023-07-25 16:09 UTC
Labels: engineering, Initiative 2
